### ISSUE TITLE
How to Obtaining the hardware and object 𝜇-maps

### ISSUE THREAD

**Issue by chestnut111** [NiftyPET/NIPET#12]
when i run :
`# obtain the hardware mu-map (the bed and the head&neck coil)
muhdct = nipet.hdw_mumap(datain, [1,2,4], mMRpars, outpath=opth, use_stored=True)
# obtain the MR-based human mu-map
muodct = nipet.obj_mumap(datain, mMRpars, outpath=opth, store=True)`
i get the information as fellow:
`IOError                                   Traceback (most recent call last)
<ipython-input-34-db9eca69d475> in <module>()
      1 # obtain the hardware mu-map (the bed and the head&neck coil)
----> 2 muhdct = nipet.hdw_mumap(datain, [1,2,4], mMRpars, outpath=opth, use_stored=False)
      3 # obtain the MR-based human mu-map
      4 muodct = nipet.obj_mumap(datain, mMRpars, outpath=opth, store=True)

/public/lixin/.local/lib/python2.7/site-packages/niftypet/nipet/img/mmrimg.pyc in hdw_mumap(datain, hparts, params, outpath, use_stored, del_interm)
   1288     # otherwise generate it from the parts through resampling the high resolution CT images
   1289     else:
-> 1290         hmupos = get_hmupos(datain, hparts, Cnt, outpath=outpath)
   1291         # just to get the dims, get the ref image
   1292         nimo = nib.load(hmupos[0]['niipath'])

/public/lixin/.local/lib/python2.7/site-packages/niftypet/nipet/img/mmrimg.pyc in get_hmupos(datain, parts, Cnt, outpath)
   1203         fh = os.path.join(Cnt['HMUDIR'], Cnt['HMULIST'][i-1])
   1204         # get the interfile header and binary data
-> 1205         hdr, im = rd_hmu(fh)
   1206         #get shape, origin, offset and voxel size
   1207         s = hmu_shape(hdr)

/public/lixin/.local/lib/python2.7/site-packages/niftypet/nipet/img/mmrimg.pyc in rd_hmu(fh)
   1066 def rd_hmu(fh):
   1067     #--read hdr file--
-> 1068     f = open(fh, 'r')
   1069     hdr = f.read()
   1070     f.close()

IOError: [Errno 2] No such file or directory: '/public/admin/umap_HNMCL_10606489.v.hdr'`

**Comment by pjmark** [comment]
Hello

That may mean that either you don't have the hardware mu-maps (must be obtained from the scanner) or the path to the mu-maps is incorrect.

Best,
Pawel
________________________________

**Comment by chestnut111** [comment]
![image](https://user-images.githubusercontent.com/26037045/70619597-51967e00-1c50-11ea-9f73-ea1fb6122bb6.png)
There are default parameters, but there are no files in this path

**Comment by pjmark** [comment]
You need to get the files from a mMR scanner. The mu-maps are not provided by the software, these are provided by Siemens for each scanner.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chestnut111** [comment]
get it..
thx!
