### ISSUE TITLE
export HMUDIR not respected

### ISSUE THREAD

**Issue by rijobro** [NiftyPET/NIPET#17]
As per https://github.com/NiftyPET/NIPET/blob/master/README.rst#quick-install, I did `export PATHTOOLS=$HOME/NiftyPET_tools`. However, on `pip install`, I still get asked (twice) for mu-map directory. Annoying when working on a slow X11.

**Comment by casperdcl** [comment]
hmm `DISPLAY='' pip install` works for me. The current logic will always prompt if DISPLAY is set. Maybe should be changed.

**Comment by rijobro** [comment]
Just a heads up, I tried with `DISPLAY='' pip install` the other day, and it errored out.

**Comment by rijobro** [comment]
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/rich/NiftyPET/nipet/setup.py", line 125, in <module>
        Tk().withdraw()
      File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1828, in __init__
        self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
    _tkinter.TclError: couldn't connect to display ""
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by casperdcl** [comment]
Ah I see you're still using python2.7... Niftypet will be dropping it before 2021.

Try using py3.6+ and the `dev2` branch for now (https://github.com/NiftyPET/NIPET/blob/dev2/README.rst#quick-install)...

Note the location of the includes has changed slightly (so you'd need to change that wrapping in SIRF too)./

Should really be providing a proper CMake package.

**Comment by rijobro** [comment]
Sounds like you're making progress on the python3 release which is good! I'll try it out next time I do a fresh install.
