### ISSUE TITLE
No module named dinf

### ISSUE THREAD

**Issue by rijobro** [NiftyPET/NIPET#18]
Normally I simply `pip install niftypet` and everything works fine. I want to modify the source code, so `git clone` both `nipet` and `nimpa`. I use `pip install` as per [the readthedocs](https://niftypet.readthedocs.io/en/latest/install.html#from-source-using-git-and-pip-setup-py) and [the readme](https://github.com/NiftyPET/NIPET#quick-install):
```
pip install --no-binary :all: --verbose -e .
```
and then test:
```
python -c "from niftypet import nipet"
```
Error: 
```
No module named dinf
```

**Comment by rijobro** [comment]
However,
```
pip uninstall -y nimpa nipet
cd <nipet source>
pip install --no-binary :all: --verbose -e .
python -c "from niftypet import nipet"
```
does work. It seems that `nipet` wants to install `nimpa` anyway, and pre-installing it just creates problems.

**Comment by casperdcl** [comment]
FYI if you run `import X` in a directory containing `X.py` or `X/__init__.py` this can confuse python.

I presume you ran `python -c "from niftypet import nipet"` in nimpa's source directory so Python couldn't find `nipet`. Simply `cd` elsewhere to fix.

**Comment by rijobro** [comment]
I haven't got any way of checking now, but the fact that it worked after uninstalling makes me think that it wasn't related to which folder I was in.
