### ISSUE TITLE
Bug in reconstruction pipeline

### ISSUE THREAD

**Issue by eric2302** [NiftyPET/NIPET#43]
The function `mmrchain` in the pipeline code `pipe.py` takes in a time frame, converts it into a dictionary and then tries to index it (e.g. [here](https://github.com/NiftyPET/NIPET/blob/b1c3799c4a795e1db34dc36decd197ab74e95c6e/niftypet/nipet/img/pipe.py#L115)).
This results in an error since dictionaries cannot be sliced.

Shouldn't the timing variable be `t_frms = dfrms['timings'][1:]`?

**Comment by pjmark** [comment]
dfrms['timings'] is a list, which is inside the dictionary.  if you get a problem here that means there is another problem somewhere else

**Comment by pjmark** [comment]
have also look at here:
https://niftypet.readthedocs.io/en/latest/tutorials/dynrecon/

**Comment by casperdcl** [comment]
Yes, this is a bug. Also near-identical definitions:

https://github.com/NiftyPET/NIPET/blob/b1c3799c4a795e1db34dc36decd197ab74e95c6e/niftypet/nipet/img/auximg.py#L73

https://github.com/NiftyPET/NIPET/blob/b1c3799c4a795e1db34dc36decd197ab74e95c6e/niftypet/nipet/lm/mmrhist.py#L492
