### ISSUE TITLE
mmr_lmproc.hist

### ISSUE THREAD

**Issue by sanazkaviani** [NiftyPET/NIPET#45]
Hello,
I have a problem with "mmr_lmproc.hist". Although I've installed the niftypet without any problem or error, my notebook crashes when I want to produce Sinogram with "mmr_lmproc.hist". I am using the "Tesla V100-SXM2-32GB" GPU.

**Comment by casperdcl** [comment]
potentially duplicate of #42?

**Comment by sanazkaviani** [comment]
Thanks for your reply.
I've already solved the problem.

**Comment by casperdcl** [comment]
Ah what was the problem/solution?
